### ISSUE TITLE
[Epic] Provide implementation for GPTCache using Vector Search

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#30]
https://gptcache.readthedocs.io/en/latest/index.html#roadmap

- [ ] Do some research on GPTCache
- [ ] Find a beta customer

**Comment by karlunho-datastax** [comment]
- [ ] Do some research on GPTCache
- [ ] Find a beta customer

**Comment by xingh** [comment]
- Details
  - Has examples for Langchain, LlamaIndex, OpenAI, 
  - User chooses cachebase, vectorbase so we can implement both. Cassandra can handle Cache requests as well as vectorsearch requests
    - data_manager = get_data_manager(CacheBase("mysql"), VectorBase("milvus", dimension=128), max_size=100, eviction='LRU') 
  - Once cache is initialized, the rest of the operations seem to use it in the background without having too much knowledge about what is happening. 
  - Interesting that now they have a dockerized version that allows use of GPTCache from different programming frameworks. 
    - YAML
    ```
      - embedding:
        - onnx
      - embedding_config:
        - # Set embedding model params here
      - storage_config:
        - data_dir:
          - gptcache_data
        - manager:
          - sqlite,faiss
        - vector_params:
          - # Set vector storage related params here
      - evaluation:
        - distance
      - evaluation_config:
        - # Set evaluation metric kws here
      - pre_function:
        - get_prompt
      - post_function:
        - first
      - config:
        - similarity_threshold: 0.8
        - # Set other config here
      ```
    - CURL Use
      ```
      - curl -X 'POST' \
        - 'http://localhost:8000/get' \
        - -H 'accept: application/json' \
        - -H 'Content-Type: application/json' \
        - -d '{
        - "prompt": "Hi"
      - }'
      ```
- Outcome
  - Create CacheBase for GPTCache using Cassandra only or Cassio?
  - Create VectorBsae for GPTCache using Vector Search/ Cassio 
- References
  - https://gptcache.readthedocs.io/en/latest/index.html#roadmap
  - https://github.com/zilliztech/GPTCache/tree/main/examples#How-to-set-the-data-manager-class
  - https://github.com/zilliztech/GPTCache/blob/main/docs/usage.md#Use-GPTCache-server
